### ISSUE TITLE
Peers-Review

### ISSUE THREAD

**Issue by Moathal** [skyv26/awesome-book-modular-es6#2]
#### Despite it is perfection and after a long review  and trying to find a piece of hair  in a pile of straws, I found  a very few things to say 😫 

- I would rather collect all the functions in another module and call the from the main JavaScript.
- I also would put all the variables on the top of the main module right below the import section.

**Comment by skyv26** [comment]
# Hi @Moathal,

Thank you so much for your valuable feedback. Actually it is Low-Fidelity Design project. Soon I will upload `version-2` of this project with awesome UI for Awesome Books. Feel free to contact me.

Happy Coding 🥂
